export default {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    TOGGLE_ALL_CATEGORIES_MATCHED: 'TOGGLE_ALL_CATEGORIES_MATCHED'
}
