export default {
    USER_OAUTH2_LOGIN_URL_GET_REQUEST: 'USER_OAUTH2_LOGIN_URL_GET_REQUEST',
    USER_OAUTH2_LOGIN_URL_GET_SUCCESS: 'USER_OAUTH2_LOGIN_URL_GET_SUCCESS',
    USER_OAUTH2_LOGIN_URL_GET_FAILURE: 'USER_OAUTH2_LOGIN_URL_GET_FAILURE',
    USER_OAUTH2_LOGIN_REQUEST: 'USER_OAUTH2_LOGIN_REQUEST',
    USER_OAUTH2_LOGIN_SUCCESS: 'USER_OAUTH2_LOGIN_SUCCESS',
    USER_OAUTH2_LOGIN_FAILURE: 'USER_OAUTH2_LOGIN_FAILURE',
    USER_OAUTH2_REFRESH_ACCESS_TOKEN_REQUEST:
        'USER_OAUTH2_REFRESH_ACCESS_TOKEN_REQUEST',
    USER_OAUTH2_REFRESH_ACCESS_TOKEN_SUCCESS:
        'USER_OAUTH2_REFRESH_ACCESS_TOKEN_SUCCESS',
    USER_OAUTH2_REFRESH_ACCESS_TOKEN_FAILURE:
        'USER_OAUTH2_REFRESH_ACCESS_TOKEN_FAILURE',
    USER_OAUTH2_LOGOUT_REQUEST: 'USER_OAUTH2_LOGOUT_REQUEST',
    USER_OAUTH2_LOGOUT_SUCCESS: 'USER_OAUTH2_LOGOUT_SUCCESS',
    USER_OAUTH2_LOGOUT_FAILURE: 'USER_OAUTH2_LOGOUT_FAILURE',
    GET_ME_REQUEST: 'GET_ME_REQUEST',
    GET_ME_SUCCESS: 'GET_ME_SUCCESS',
    GET_ME_FAILURE: 'GET_ME_FAILURE',
    GET_USER_LOCATION_REQUEST: 'GET_USER_LOCATION_REQUEST',
    GET_USER_LOCATION_SUCCESS: 'GET_USER_LOCATION_SUCCESS',
    GET_USER_LOCATION_FAILURE: 'GET_USER_LOCATION_FAILURE',
    SET_USER_MAP_DISTANCE: 'SET_USER_MAP_DISTANCE'
}
