export default {
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',
    TOGGLE_DRAWER_POSITION: 'TOGGLE_DRAWER_POSITION',
    TOGGLE_HEADER: 'TOGGLE_HEADER',
    TOGGLE_HEADER_POP: 'TOGGLE_HEADER_POP',
    TOGGLE_HEADER_POSITION: 'TOGGLE_HEADER_POSITION',
    TOGGLE_NAVBAR: 'TOGGLE_NAVBAR',
    TOGGLE_NAVBAR_POP: 'TOGGLE_NAVBAR_POP',
    TOGGLE_NAVBAR_POSITION: 'TOGGLE_NAVBAR_POSITION'
}
